{
 "title": "Words",
 "time": { "from": "now-1y/y", "to": "now-1y/y" },
 "panels": [
  {
   "title": "Words by languages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(NOW()) as time_sec,\n  count(words.id) as value,\n  languages.name as metric\nFROM words\nINNER JOIN languages ON words.lang_id = languages.id\nGROUP BY lang_id\n"
    }
   ]
  },
  {
   "title": "Words with most hits",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT words.name, count(words.id) as count_words\r\nFROM steps \r\nINNER JOIN words ON steps.word_question_id = words.id\r\nWHERE steps.result_answer = 1\r\nGROUP BY words.id\r\nORDER BY count_words DESC\r\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Words with most misses",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT words.name, count(words.id) as count_words\r\nFROM steps \r\nINNER JOIN words ON steps.word_question_id = words.id\r\nWHERE time_give IS NOT NULL AND time_received IS NULL\r\nGROUP BY words.id\r\nORDER BY count_words DESC"
    }
   ]
  }
 ]
}